apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/bank-vaults/vault-operator/tree/a98518c8ddb8352ad6c0709d2a0da2e983b6dfda/deploy/rbac
  - vault.yaml
  - ingress.yaml
