apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: example
    role: alert-rules
  name: myfirstrule
  namespace: default
spec:
  groups:
  - name: myrulegroup
    interval: 60s
    rules:
    - alert: Alert
      expr: count(coredns_dns_requests_total) > 2
      for: 1m
      labels:
        severity: warning
        notification: telegram
      annotations:
        description: "ingress"
