apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: example
    role: alert-rules
  name: myfirstrule
  namespace: default
spec:
  groups:
  - name: myrulegroup
    interval: 60s
    rules:
    - alert: Alert
      expr: sum(rate(nginx_ingress_controller_requests{status=~'5..'}[1m])) by (ingress,cluster) / sum(rate(nginx_ingress_controller_requests[1m])) by (ingress) * 100 > 5
      for: 1m
      labels:
        severity: warning
        notification: telegram
      annotations:
        description: "ingress"
