apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres
resources:
  - namespace.yaml
  - release.yaml
  - secret.yaml
  - backup.yaml
  - postgres-recovery.yaml
  - secret-recovery.yaml
configMapGenerator:
  - name: postgresql-values 
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml