apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-recovery # Название кластера.
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: yc-network-hdd
    size: 1Gi
  bootstrap:    
    initdb: # Развертывание нового кластера.
      database: grafana
      owner: grafana
      secret:
        name: grafana-pg-user
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: "1d"
    barmanObjectStore:
      destinationPath: "s3://evronelabs-postgresql-store" # Путь к каталогу.
      endpointURL: "https://storage.yandexcloud.net" # Сервис S3.
      s3Credentials: # Данные для доступа к bucket’у.
        accessKeyId:
          name: postgres-aws
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: postgres-aws
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: gzip # Включено сжатие WAL.