apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: grafana-pg # Название кластера.
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: local
    size: 1Gi
  bootstrap:
    initdb: # Развертывание нового кластера.
      database: grafana
      owner: grafana
      # secret:
      #   name: grafana-pg-user
  monitoring:
    enablePodMonitor: false
  backup:
  retentionPolicy: 14
  barmanObjectStore:
    destinationPath: "s3://evronelabs-prometheus-store/backups" # Путь к каталогу.
    endpointURL: "https://storage.yandexcloud.net" # Сервис S3.
    s3Credentials: # Данные для доступа к bucket’у.
      accessKeyId:
        name: s3-creds
        key: YCAJE4TM_oVlS5edgGF9sSeHv
      secretAccessKey:
        name: s3-creds
        key: YCMnd81ev6QUkQcGkfiASD0piHl1NdNqbKRSlA1k
    wal:
      compression: gzip # Включено сжатие WAL.