apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: grafana-pg # Название кластера.
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: local
    size: 1Gi
  bootstrap:
    initdb: # Развертывание нового кластера.
      database: grafana
      owner: grafana
      secret:
        name: grafana-pg-user
  monitoring:
    enablePodMonitor: false