apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerts
  labels:
    grafana_alert: "1"
data:
  my-alert.json: |
    {
      "apiVersion": 1,
      "groups": [
        {
          "name": "my_rule_group",
          "rules": [
            {
              "alert": "HighErrorRate",
              "expr": "sum(rate(nginx_ingress_controller_requests{status=~'5..'}[1m])) by (ingress,cluster) / sum(rate(nginx_ingress_controller_requests[1m]))by (ingress) * 100 > 5",
              "for": "1m",
              "labels": {
                "severity": "warning"
              },
              "annotations": {
                "summary": "High error rate on {{ $labels.ingress }}",
                "description": "{{ $labels.ingress }} has an error rate of {{ $value }}%. Expected less than 5%."
              }
            }
          ]
        }
      ]
    }
