apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alert
  labels:
    grafana_alert: "1"
data: 
  alert: |
      apiVersion: 1
      groups:
        - orgId: 1
          name: 'my_rule_group'
          folder: my_first_folder
          interval: 60s
          rules:
            - uid: my_id_1
              title: my_first_rule
              condition: A
              data:
                - refId: A
                  datasourceUid: '-100'
                  model:
                    conditions:
                    - alert: Alert
                      expr: sum(rate(nginx_ingress_controller_requests{status=~'5..'}[1m])) by (ingress,cluster) / sum(rate(nginx_ingress_controller_requests[1m]))by (ingress) * 100 > 5
                      for: 1m
              annotations:
                description: "{{ $labels.ingress }} has an error rate of {{ $value }}%. Expected less than 5%."
              labels:
                severity: warning