---
admin:
  existingSecret: grafana-admin

tolerations:
  - key: environment
    operator: Equal
    value: infra
    effect: NoSchedule

persistence:
  enabled: false

# ingress:
#   enabled: true
#   ingressClassName: nginx
#   annotations:
#     external-dns.alpha.kubernetes.io/hostname: grafana.
#     # Authentication
#     nginx.ingress.kubernetes.io/auth-url: ""
#     nginx.ingress.kubernetes.io/auth-signin: ""
#   hosts:
#   - grafana.
#   path: /
#   tls:
#     - hosts:
#       - grafana.
#       secretName: "matyshkin-com-wildcard-tls" 

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.loki:3100
      jsonData:
        maxLines: 1000