---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mat-test-flux
spec:
  secretName: matyshkin-com-wildcard-tls
  secretTemplate:
    annotations:
      replicator.v1.mittwald.de/replicate-to: development,production,weave-gitops,grafana,vault,oauth2-proxy
  issuerRef:
    name: matyshkin-com
    kind: ClusterIssuer
  commonName: "*.infra.matyshkinm.evrone.app"
  dnsNames:
  - ".infra.matyshkinm.evrone.app"
  - "*.infra.matyshkinm.evrone.app"