# nginx:
#   ingress:
#     enabled: true
#     annotations: 
#       cert-manager.io/cluster-issuer: letsencrypt-prod
#       # kubernetes.io/ingress.class: nginx
#       # kubernetes.io/tls-acme: "true"
#     path: /
#     pathType: Prefix
#     hosts:
#         - mimir.infra.matyshkinm.evrone.app
#     tls: 
#     -   secretName: matyshkin-com-mimir-tls
#         hosts:
#         - mimir.infra.matyshkinm.evrone.app

alertmanager:
  enabled: true
ingester:
  zoneAwareReplication:
    enabled: false
store_gateway:
  zoneAwareReplication:
    enabled: false
rollout_operator:
  enabled: false


# alertmanager:
#   zoneAwareReplication:
#     topologyKey: "kubernetes.io/hostname" # Triggers creating anti-affinity rules
#     zones:
#       - name: zone-a
#         nodeSelector:
#           topology.kubernetes.io/zone: us-central1-a
#       - name: zone-b
#         nodeSelector:
#           topology.kubernetes.io/zone: us-central1-b
#       - name: zone-c
#         nodeSelector:
#           topology.kubernetes.io/zone: us-central1-c



global:
  extraEnvFrom:
    - secretRef:
        name: aws-credentials
  podAnnotations:
    bucketSecretVersion: "0"

minio:
  enabled: false

mimir:
  structuredConfig:
    admin_client:
      storage:
        s3:
      endpoint   : "storage.yandexcloud.net"
      region     : "ru-central1"
    alertmanager_storage:
      s3:
      bucket_name: "evronelabs-victoriametrics-store"
    blocks_storage:
      backend: s3
      s3:
      bucket_name: "evronelabs-victoriametrics-store"
    ruler_storage:
      s3:
      bucket_name: "evronelabs-victoriametrics-store"


    # usage_stats:
    #     installation_mode: helm

    #   activity_tracker:
    #     filepath: /active-query-tracker/activity.log

    # alertmanager_storage:
    # backend: s3
    # s3:
    #   endpoint   : "storage.yandexcloud.net"
    #   bucket_name: "evronelabs-victoriametrics-store"
    #   region     : "ru-central1"