# nginx:
#   ingress:
#     enabled: true
#     annotations: 
#       cert-manager.io/cluster-issuer: letsencrypt-prod
#       # kubernetes.io/ingress.class: nginx
#       # kubernetes.io/tls-acme: "true"
#     path: /
#     pathType: Prefix
#     hosts:
#         - mimir.infra.matyshkinm.evrone.app
#     tls: 
#     -   secretName: matyshkin-com-mimir-tls
#         hosts:
#         - mimir.infra.matyshkinm.evrone.app
alertmanager:
  persistentVolume:
    enabled: fals
  replicas: 2
  resources:
    limits:
      memory: 1.4Gi
    requests:
      cpu: 1
      memory: 1Gi
  statefulSet:
    enabled: true

compactor:
  persistentVolume:
    size: 20Gi
  resources:
    limits:
      memory: 2.1Gi
    requests:
      cpu: 1
      memory: 1.5Gi

distributor:
  replicas: 2
  resources:
    limits:
      memory: 5.7Gi
    requests:
      cpu: 2
      memory: 4Gi

ingester:
  persistentVolume:
    size: 50Gi
  replicas: 3
  resources:
    limits:
      memory: 12Gi
    requests:
      cpu: 3.5
      memory: 8Gi
  topologySpreadConstraints: {}
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: target # support for enterprise.legacyLabels
                operator: In
                values:
                  - ingester
          topologyKey: 'kubernetes.io/hostname'

        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                  - ingester
          topologyKey: 'kubernetes.io/hostname'

  zoneAwareReplication:
    topologyKey: 'kubernetes.io/hostname'

admin-cache:
  enabled: true
  replicas: 2

chunks-cache:
  enabled: true
  replicas: 2

index-cache:
  enabled: true
  replicas: 3

metadata-cache:
  enabled: true

results-cache:
  enabled: true
  replicas: 2

minio:
  enabled: false

overrides_exporter:
  replicas: 1
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

querier:
  replicas: 1
  resources:
    limits:
      memory: 5.6Gi
    requests:
      cpu: 2
      memory: 4Gi

query_frontend:
  replicas: 1
  resources:
    limits:
      memory: 2.8Gi
    requests:
      cpu: 2
      memory: 2Gi

ruler:
  replicas: 1
  resources:
    limits:
      memory: 2.8Gi
    requests:
      cpu: 1
      memory: 2Gi

store_gateway:
  persistentVolume:
    size: 10Gi
  replicas: 3
  resources:
    limits:
      memory: 2.1Gi
    requests:
      cpu: 1
      memory: 1.5Gi
  topologySpreadConstraints: {}
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: target # support for enterprise.legacyLabels
                operator: In
                values:
                  - store-gateway
          topologyKey: 'kubernetes.io/hostname'

        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                  - store-gateway
          topologyKey: 'kubernetes.io/hostname'
  zoneAwareReplication:
    topologyKey: 'kubernetes.io/hostname'

nginx:
  replicas: 1
  resources:
    limits:
      memory: 731Mi
    requests:
      cpu: 1
      memory: 512Mi

# Grafana Enterprise Metrics feature related
admin_api:
  replicas: 1
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

gateway:
  replicas: 1
  resources:
    limits:
      memory: 731Mi
    requests:
      cpu: 1
      memory: 512Mi


# alertmanager:
#   enabled: true
# ingester:
#   zoneAwareReplication:
#     enabled: false
# store_gateway:
#   zoneAwareReplication:
#     enabled: false
rollout_operator:
  enabled: false


# alertmanager:
#   zoneAwareReplication:
#     topologyKey: "kubernetes.io/hostname" # Triggers creating anti-affinity rules
#     zones:
#       - name: zone-a
#         nodeSelector:
#           topology.kubernetes.io/zone: us-central1-a
#       - name: zone-b
#         nodeSelector:
#           topology.kubernetes.io/zone: us-central1-b
#       - name: zone-c
#         nodeSelector:
#           topology.kubernetes.io/zone: us-central1-c



global:
  extraEnvFrom:
    - secretRef:
        name: aws-credentials
  podAnnotations:
    bucketSecretVersion: "0"

# minio:
#   enabled: false

mimir:
  structuredConfig:
    admin_client:
      storage:
        s3:
      endpoint   : "storage.yandexcloud.net"
      region     : "ru-central1"
    alertmanager_storage:
      s3:
      bucket_name: "evronelabs-victoriametrics-store"
    blocks_storage:
      backend: s3
      s3:
      bucket_name: "evronelabs-victoriametrics-store"
    ruler_storage:
      s3:
      bucket_name: "evronelabs-victoriametrics-store"


    # usage_stats:
    #     installation_mode: helm

    #   activity_tracker:
    #     filepath: /active-query-tracker/activity.log

    # alertmanager_storage:
    # backend: s3
    # s3:
    #   endpoint   : "storage.yandexcloud.net"
    #   bucket_name: "evronelabs-victoriametrics-store"
    #   region     : "ru-central1"