apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ingress-controller
  - ./cert-manager-items
  - ./loki
  - ./grafana
  # - ./prometheus
  # - ./victoria-metrics
  # - ./mimir
  # - ./linkerd-viz
  - ./postgresql
  # - ./linkerd
  - ./linkerd2
  - ./banzaicloud