apiVersion: v1
kind: Secret
metadata:
  name: secret-tls
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJqakNDQVRTZ0F3SUJBZ0lSQUxyMS9nNmp5QmdraHNTNHdHTVBRN1F3Q2dZSUtvWkl6ajBFQXdJd0pURWoKTUNFR0ExVUVBeE1hY205dmRDNXNhVzVyWlhKa0xtTnNkWE4wWlhJdWJHOWpZV3d3SGhjTk1qTXhNVEEzTVRFeQpOVFF5V2hjTk16TXhNVEEwTVRFeU5UUXlXakFsTVNNd0lRWURWUVFERXhweWIyOTBMbXhwYm10bGNtUXVZMngxCmMzUmxjaTVzYjJOaGJEQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJJUExvZ2kwblI2anJFWTMKdUwvTlBYR0xtQTFzdWZPK2tpcWJpc1NwUE9QVkJvWjh4U1FvSW96VTdHZmY2RDBucmI1dythZ2R1ZCtvZWJaOApsTHU1KzF1alJUQkRNQTRHQTFVZER3RUIvd1FFQXdJQkJqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUJNQjBHCkExVWREZ1FXQkJRNHJmWGowbjgreHQ1Q2REdUV0cERsM1ZkS0JEQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUEKeXR2SFRLdm9CRllFaytQd2xJWVNTR0E4djNTVzl6Z2FFUWlOMk9zeXQxQUNJQWFWUkFSNEh0ZnZMNlFEaWFnVwpoWE1xZFlITER0RlRiVk4zellLdDlQajgKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  
  tls.key: |
    LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUVRMEc0ZDZOcVU0Q0NLRDhvSXEvWWlJSU5VRk5Ha2Y4RStCZDI4SVB4VWtvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFZzh1aUNMU2RIcU9zUmplNHY4MDljWXVZRFd5NTg3NlNLcHVLeEtrODQ5VUdobnpGSkNnaQpqTlRzWjkvb1BTZXR2bkQ1cUIyNTM2aDV0bnlVdTduN1d3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
