apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  grafana_alert: "1"
configMapGenerator:
  - name: grafana-alert
    files:
      - alert.yaml
generatorOptions:
  disableNameSuffixHash: true