apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: controller-manager-metrics-monitor
spec:
  selector:
    matchLabels:
      Release:  "prometheus"
      app.kubernetes.io/name: cloudnative-pg
  podMetricsEndpoints:
    - port: metrics