apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    Release:  prometheus
    app.kubernetes.io/name: cloudnative-pg
  name: controller-manager-metrics-monitor
  namespace: postgres
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
  podMetricsEndpoints:
    - port: metrics
    