apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
spec:
  interval: 1m0s
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    adminUser:
      create: true
      passwordHash: qwertyzxc123
      username: "admin"
    ingress:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/hostname: ---
        # Authentication
        nginx.ingress.kubernetes.io/auth-url: ----
        nginx.ingress.kubernetes.io/auth-signin: ---
      tls:
        - hosts:
          - ----
          secretName: ----
      hosts:
      - host: ---
        paths:
          - path: /
            pathType: ImplementationSpecific
    tolerations:
      - key: environment
        operator: Equal
        value: infra
        effect: NoSchedule