---
server:
  scrape:
    enabled: true
  # admissionWebhooks:
  #   patch:
  #     tolerations:
  #       - key: environment
  #         operator: Equal
  #         value: infra
  #         effect: NoSchedule
  # tolerations:
  #   - key: environment
  #     operator: Equal
  #     value: infra
  #     effect: NoSchedule

# remote_write:
#   - url: http://mimir.infra.matyshkinm.evrone.app/api/v1/push

