---
server:
  scrape:
    enabled: true
  # admissionWebhooks:
  #   patch:
  #     tolerations:
  #       - key: environment
  #         operator: Equal
  #         value: infra
  #         effect: NoSchedule
  # tolerations:
  #   - key: environment
  #     operator: Equal
  #     value: infra
  #     effect: NoSchedule