apiVersion: v1
kind: Secret
metadata:
  name: linkerd-secret-bundle
stringData:
  ca.crt: | 
    -----BEGIN CERTIFICATE-----
    MIIBjDCCATOgAwIBAgIQYv/1g2oV1A9yFpddmij31zAKBggqhkjOPQQDAjAlMSMw
    IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yMzExMDIwODAx
    MzVaFw0zMzEwMzAwODAxMzVaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5jbHVz
    dGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEDH7ynEZ8FOsG2S5T
    uzYWMZjpcUhy716rlQQjWlYi6S1YaqN0wLHchHJ3SdKpjEAgTyrEKxSmpcpC9eiE
    SvZbm6NFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYD
    VR0OBBYEFHKsa86+Kex0+bNPuw19WKYKbQHfMAoGCCqGSM49BAMCA0cAMEQCIBUN
    jbPSSzVphF1cuz1XHznCwsYRrBqjGUm0E8SNDGS8AiAbbm7hMSlVXfRYwgl/1QTA
    EkrORzMr41om7+jfblM7SA==
    -----END CERTIFICATE----- 
