apiVersion: v1
kind: Secret
metadata:
  name: linkerd-trust-anchor
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBsjCCAVigAwIBAgIQNsXPzt8aiQcPhOuakJ9flDAKBggqhkjOPQQDAjAlMSMw
    IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yMzExMDIwODAx
    NDlaFw0yNDExMDEwODAxNDlaMCkxJzAlBgNVBAMTHmlkZW50aXR5LmxpbmtlcmQu
    Y2x1c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABKuSW77RUGh4
    3qmBvP3MREoe42boFZqsSo5FAQCsS7FcgKLSBPLedXLz8gFZZdWFCtYtr3+11SOz
    vB/uFZOCrcejZjBkMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEA
    MB0GA1UdDgQWBBROV/C52soXLd2CVQ0/OwO6EIFryTAfBgNVHSMEGDAWgBRyrGvO
    vinsdPmzT7sNfVimCm0B3zAKBggqhkjOPQQDAgNIADBFAiEAugIi14h2zZ7vkfMI
    3gb8xZ/GI+X68oDWgdRtP2w096ECICaeHkqoGdgKVVojmbB89Csx5gcVXs5/vEF3
    6XWXutuA
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIH4O8GAun8caozjHsuyPVsOnyja3NEfaYxWDfu4SxxdFoAoGCCqGSM49
    AwEHoUQDQgAEq5JbvtFQaHjeqYG8/cxESh7jZugVmqxKjkUBAKxLsVyAotIE8t51
    cvPyAVll1YUK1i2vf7XVI7O8H+4Vk4Ktxw==
    -----END EC PRIVATE KEY-----