apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: thanos
#   annotations:
#     vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
#     vault.security.banzaicloud.io/vault-role: "default"
#     vault.security.banzaicloud.io/vault-tls-secret: vault-tls
#     vault.security.banzaicloud.io/vault-path: "kubernetes"
# stringData:
#   object-store.yaml: "vault:fluxcd/data/thanos#object_store"


stringData: 
  object-store.yaml: |
    type: S3
    config:
      endpoint    : "storage.yandexcloud.net"
      bucket      : "evronelabs-prometheus-store"
      region      : "ru-central1"
      access_key  : "YCAJE4TM_oVlS5edgGF9sSeHv"
      secret_key  : "YCMnd81ev6QUkQcGkfiASD0piHl1NdNqbKRSlA1k" 

#       {}