apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: thanos-secret
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
    vault.security.banzaicloud.io/vault-role: "default"
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
    vault.security.banzaicloud.io/vault-path: "kubernetes"
stringData:
  object-store.yaml: "vault:fluxcd/data/thanos#object_store"