apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: thanos
stringData: 
  object-store.yaml: |
    type: S3
    config:
      endpoint    : "storage.yandexcloud.net"
      bucket      : "evronelabs-prometheus-store"
      region      : "ru-central1"
      access_key  : "YCAJE4TM_oVlS5edgGF9sSeHv"
      secret_key  : "YCMnd81ev6QUkQcGkfiASD0piHl1NdNqbKRSlA1k" 