global:
  imagePullSecrets:
    - name:  aws-credentials

prometheus:
  prometheusSpec:
    thanos:
      secret:
        type: s3
        config:
          endpoint    : "storage.yandexcloud.net"
          bucketnames : "evronelabs-prometheus-store"
          region      : "ru-central1"

grafana:
  enabled: false




# ---
# prometheus:
#   prometheusSpec:
#     thanos:
#       # ObjectStorageConfig configures object storage in Thanos.
#       objectStorageConfig:
#         # use existing secret, if configured, objectStorageConfig.secret will not be used
#         existingSecret:
#           name: thanos-secret
#           key: object-store.yaml
#     tolerations:
#       - key: environment
#         operator: Equal
#         value: infra
#         effect: NoSchedule
alertmanager:
  alertmanagerSpec:
    tolerations:
      - key: environment
        operator: Equal
        value: infra
        effect: NoSchedule
prometheusOperator:
  tolerations:
    - key: environment
      operator: Equal
      value: infra
      effect: NoSchedule
  admissionWebhooks:
    patch:
      tolerations:
        - key: environment
          operator: Equal
          value: infra
          effect: NoSchedule
thanosRuler:
  thanosRulerSpec:
    tolerations:
      - key: environment
        operator: Equal
        value: infra
        effect: NoSchedule
# grafana:
#   enabled: false