prometheus:
  podAnnotations:
  linkerd.io/inject: enabled
  # extraSecret:
  #   name: aws-credentials
  prometheusSpec:
    thanos:
      blockSize: 5h
      # image: quay.io/thanos/thanos:v0.28.1
      objectStorageConfig:
        existingSecret:
          name: www
          key: object-store.yaml
    tolerations:
      - key: environment
        operator: Equal
        value: infra
        effect: NoSchedule
        # secret:
        #   type: S3
        #   config:
        #     endpoint    : "storage.yandexcloud.net"
        #     bucket      : "evronelabs-prometheus-store"
        #     region      : "ru-central1"
        #     aws_sdk_auth: true
        #     signature_version2: true
            # access_key  : "YCAJE4TM_oVlS5edgGF9sSeHv"
            # secret_key  : "YCMnd81ev6QUkQcGkfiASD0piHl1NdNqbKRSlA1k" 
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    scrapeConfigSelectorNilUsesHelmValues: false

  ingress:
    enabled: true
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    paths: 
      - /
    pathType: Prefix
    hosts:
        - prometheus.infra.matyshkinm.evrone.app
    tls: 
    -   secretName: matyshkin-com-prometheus-tls
        hosts:
        - prometheus.infra.matyshkinm.evrone.app

grafana:
  enabled: false
thanosRuler:
  thanosRulerSpec:
    tolerations:
      - key: environment
        operator: Equal
        value: infra
        effect: NoSchedule  
prometheusOperator:
  tolerations:
    - key: environment
      operator: Equal
      value: infra
      effect: NoSchedule
  admissionWebhooks:
    patch:
      tolerations:
        - key: environment
          operator: Equal
          value: infra
          effect: NoSchedule


alertmanager:
  alertmanagerSpec:
    tolerations:
      - key: environment
        operator: Equal
        value: infra
        effect: NoSchedule
  templateFiles:
    template_1.tmpl: |-
          {{ define "slack.text" }}
          {{- $root := . -}}
          {{ range .Alerts }}
            **Alert:** - {{ .Annotations.summary }} - `{{ .Labels.severity }}`
            **Alert started at:** - {{ .StartsAt.time.Time | humanize }}
            **Description:** - {{ .Annotations.description }}
            **Graph:** ```markdown[📈]({{ .GeneratorURL }})```
            **Details:**
              {{ range .Labels.SortedPairs }} - *{{ .Name }}:* `{{ .Value }}`
              {{ end }}
          {{ end }}
          {{ end }}

  config: 
    receivers:
     - name: telegram-test
       telegram_configs:
        - chat_id: -4054758218
          bot_token: 6924031733:AAFHyuMMY7xEDLLcQ0CP0sF4T4kIj608oq4
          api_url: "https://api.telegram.org"
          send_resolved: true
          parse_mode: HTML
          message: '{{ template "slack.text" . }}'

        - chat_id: -4020089629
          bot_token: 6801159788:AAE20ZjWrjnxV7A0ztGWLfWaADTUGQywMs0
          api_url: "https://api.telegram.org"
          send_resolved: true
          parse_mode: HTML
          message: '{{ template "slack.text" . }}'

    route:
        group_by: ['ds_id'] # Алерты группируются по UUID кластера.
        group_wait: 15s
        group_interval: 30s
        repeat_interval: 12h
        receiver: telegram-test
        routes:
          - receiver: telegram-test
            continue: true
            matchers:
            - notification="telegram"