prometheus:
  # extraSecret:
  #   name: aws-credentials
  prometheusSpec:
    thanos:
      blockSize: 2h
      # image: quay.io/thanos/thanos:v0.28.1
      objectStorageConfig:
        existingSecret:
          name: "thanos"
          key: "object-store.yaml"
        # secret:
        #   type: S3
        #   config:
        #     endpoint    : "storage.yandexcloud.net"
        #     bucket      : "evronelabs-prometheus-store"
        #     region      : "ru-central1"
        #     aws_sdk_auth: true
        #     signature_version2: true
            # access_key  : "YCAJE4TM_oVlS5edgGF9sSeHv"
            # secret_key  : "YCMnd81ev6QUkQcGkfiASD0piHl1NdNqbKRSlA1k" 
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    scrapeConfigSelectorNilUsesHelmValues: false
    
  ingress:
    enabled: true
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    paths: 
      - /
    pathType: Prefix
    hosts:
        - prometheus.infra.matyshkinm.evrone.app
    tls: 
    -   secretName: matyshkin-com-prometheus-tls
        hosts:
        - prometheus.infra.matyshkinm.evrone.app

grafana:
  enabled: false