name: terraform install infra

# on:
#   workflow_dispatch:

on:
    push:
        branches:
            - main
        paths:
            - 'terraform/infra/**/*.tf'
            - 'terraform/infra/**/*.yaml'
    pull_request:
        branches:
            - main
        paths:
            - 'terraform/infra/**/*.tf'
            - 'terraform/infra/**/*.yaml'
        
env:
    working-directory: terraform/infra
    TF_VAR_zone: ${{ vars.YC_REGION }}
    TF_VAR_cloud_id: ${{ secrets.YC_CLOUD_ID }}
    TF_VAR_token: ${{ secrets.YC_TOCKEN }}
    TF_VAR_folder_id: ${{ secrets.YC_FOLDER_ID }}
    TF_VAR_service_account_id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
    TF_VAR_github_org: ${{ github.repository_owner }}
    TF_VAR_github_repository: "test_yc_argo" 
    TF_VAR_access_key: ${{ secrets.YC_ACCESS_KEY_S3 }}
    TF_VAR_secret_key: ${{ secrets.YC_SECRET_KEY_S3 }}

jobs:
    terraform_infra:
        permissions: write-all
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{ env.working-directory }}

        steps:

        - name: Git clone my repo
          uses: actions/checkout@v4

        - name: Install terraform
          uses: hashicorp/setup-terraform@v2    
          with:
            terraform_version: 1.5.7 
            
        # - name: config terraform
        #   run : |
        #     cat <<EOF >> ~/.terraformrc
        #     provider_installation {
        #         network_mirror {
        #             url = "https://terraform-mirror.yandexcloud.net/"
        #             include = ["registry.terraform.io/*/*"]
        #         }
        #         direct {
        #             exclude = ["registry.terraform.io/*/*"]
        #         }
        #     }
        #     EOF
                
        - name: Terraform init
          run : terraform init
          # |
          #   terraform init \
          #   -backend-config="bucket=evronelabs-terraform-state-store" \
          #   -backend-config="endpoint=storage.yandexcloud.net" \
          #   -backend-config="key=infra/terraform.tfstate"
          #   -backend-config="ru-central1"

        - name: Validate
          run : terraform validate 
                    
        - name: Terraform lint
          run : terraform fmt -check 

        - name: Terraform Plan
          id: plan
          run: terraform plan -no-color
        
        - uses: actions/github-script@v6
          if: github.event_name == 'pull_request'
          env:
            PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
              #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
              #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
              <details><summary>Validation Output</summary>
        
              \`\`\`\n
              ${{ steps.validate.outputs.stdout }}
              \`\`\`
        
              </details>
        
              #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
        
              <details><summary>Show Plan</summary>
        
              \`\`\`\n
              ${process.env.PLAN}
              \`\`\`
        
              </details>
        
              *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
        
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })
        
        - name: Terraform Apply
          # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
          run : terraform apply -auto-approve